// flow-typed signature: 86391bfa8eb5fd7240e4e14189c63b61
// flow-typed version: <<STUB>>/bolt_v^0.20.5/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bolt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bolt' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bolt/bin' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/cli' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/add' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/autoclean' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/bin' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/build' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/cache/clean' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/cache/dir' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/cache/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/cache/list' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/check' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/config/current' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/config/delete' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/config/get' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/config/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/config/list' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/config/set' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/create' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/doc' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/exec' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/format' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/generate' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/global/add' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/global/bin' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/global/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/global/list' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/global/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/global/upgrade' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/help' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/import' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/info' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/init' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/install' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/licenses/generateDisclaimer' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/licenses/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/licenses/list' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/link' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/lint' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/list' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/login' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/logout' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/normalize' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/outdated' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/owner/add' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/owner/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/owner/list' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/owner/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/pack' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/project/add' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/project/exec' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/project/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/project/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/project/run' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/project/upgrade' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/publish' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/publishLock' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/publishUnlock' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/run' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/tag/add' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/tag/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/tag/list' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/tag/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/team/add' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/team/create' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/team/destroy' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/team/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/team/list' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/team/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/test' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/unlink' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/upgrade' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/upgradeInteractive' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/version' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/versions' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/why' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspace/add' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspace/exec' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspace/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspace/link' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspace/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspace/run' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspace/unlink' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspace/upgrade' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspaces/add' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspaces/exec' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspaces/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspaces/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspaces/run' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/commands/workspaces/upgrade' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/Config' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/constants' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/functions/getDependencyGraph' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/functions/getDependentsGraph' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/functions/getProject' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/functions/getWorkspaces' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/functions/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/functions/runWorkspaceTasks' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/functions/updatePackageVersions' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/functions/updateWorkspaceDependencies' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/generators/license' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/index' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/Package' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/Project' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/Repository' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/types' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/addDependenciesToPackages' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/changes' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/errors' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/execCommand' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/fs' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/git' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/globs' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/jsonModifier' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/locks' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/logger' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/messages' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/npm' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/options' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/processes' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/promises' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/prompts' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/removeDependenciesFromPackages' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/symlinkPackageDependencies' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/upgradeDependenciesInPackages' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/validateProject' {
  declare module.exports: any
}

declare module 'bolt/dist/legacy/utils/yarn' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/cli' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/add' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/autoclean' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/bin' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/build' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/cache/clean' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/cache/dir' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/cache/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/cache/list' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/check' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/config/current' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/config/delete' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/config/get' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/config/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/config/list' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/config/set' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/create' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/doc' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/exec' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/format' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/generate' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/global/add' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/global/bin' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/global/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/global/list' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/global/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/global/upgrade' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/help' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/import' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/info' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/init' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/install' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/licenses/generateDisclaimer' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/licenses/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/licenses/list' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/link' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/lint' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/list' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/login' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/logout' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/normalize' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/outdated' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/owner/add' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/owner/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/owner/list' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/owner/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/pack' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/project/add' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/project/exec' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/project/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/project/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/project/run' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/project/upgrade' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/publish' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/publishLock' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/publishUnlock' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/run' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/tag/add' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/tag/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/tag/list' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/tag/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/team/add' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/team/create' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/team/destroy' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/team/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/team/list' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/team/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/test' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/unlink' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/upgrade' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/upgradeInteractive' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/version' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/versions' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/why' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspace/add' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspace/exec' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspace/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspace/link' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspace/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspace/run' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspace/unlink' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspace/upgrade' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspaces/add' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspaces/exec' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspaces/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspaces/remove' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspaces/run' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/commands/workspaces/upgrade' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/Config' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/constants' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/functions/getDependencyGraph' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/functions/getDependentsGraph' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/functions/getProject' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/functions/getWorkspaces' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/functions/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/functions/runWorkspaceTasks' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/functions/updatePackageVersions' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/functions/updateWorkspaceDependencies' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/generators/license' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/index' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/Package' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/Project' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/Repository' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/types' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/addDependenciesToPackages' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/changes' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/errors' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/execCommand' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/fs' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/git' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/globs' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/jsonModifier' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/locks' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/logger' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/messages' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/npm' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/options' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/processes' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/promises' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/prompts' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/removeDependenciesFromPackages' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/symlinkPackageDependencies' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/upgradeDependenciesInPackages' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/validateProject' {
  declare module.exports: any
}

declare module 'bolt/dist/modern/utils/yarn' {
  declare module.exports: any
}

// Filename aliases
declare module 'bolt/bin.js' {
  declare module.exports: $Exports<'bolt/bin'>
}
declare module 'bolt/dist/legacy/cli.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/cli'>
}
declare module 'bolt/dist/legacy/commands/add.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/add'>
}
declare module 'bolt/dist/legacy/commands/autoclean.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/autoclean'>
}
declare module 'bolt/dist/legacy/commands/bin.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/bin'>
}
declare module 'bolt/dist/legacy/commands/build.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/build'>
}
declare module 'bolt/dist/legacy/commands/cache/clean.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/cache/clean'>
}
declare module 'bolt/dist/legacy/commands/cache/dir.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/cache/dir'>
}
declare module 'bolt/dist/legacy/commands/cache/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/cache/index'>
}
declare module 'bolt/dist/legacy/commands/cache/list.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/cache/list'>
}
declare module 'bolt/dist/legacy/commands/check.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/check'>
}
declare module 'bolt/dist/legacy/commands/config/current.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/config/current'>
}
declare module 'bolt/dist/legacy/commands/config/delete.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/config/delete'>
}
declare module 'bolt/dist/legacy/commands/config/get.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/config/get'>
}
declare module 'bolt/dist/legacy/commands/config/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/config/index'>
}
declare module 'bolt/dist/legacy/commands/config/list.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/config/list'>
}
declare module 'bolt/dist/legacy/commands/config/set.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/config/set'>
}
declare module 'bolt/dist/legacy/commands/create.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/create'>
}
declare module 'bolt/dist/legacy/commands/doc.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/doc'>
}
declare module 'bolt/dist/legacy/commands/exec.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/exec'>
}
declare module 'bolt/dist/legacy/commands/format.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/format'>
}
declare module 'bolt/dist/legacy/commands/generate.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/generate'>
}
declare module 'bolt/dist/legacy/commands/global/add.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/global/add'>
}
declare module 'bolt/dist/legacy/commands/global/bin.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/global/bin'>
}
declare module 'bolt/dist/legacy/commands/global/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/global/index'>
}
declare module 'bolt/dist/legacy/commands/global/list.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/global/list'>
}
declare module 'bolt/dist/legacy/commands/global/remove.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/global/remove'>
}
declare module 'bolt/dist/legacy/commands/global/upgrade.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/global/upgrade'>
}
declare module 'bolt/dist/legacy/commands/help.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/help'>
}
declare module 'bolt/dist/legacy/commands/import.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/import'>
}
declare module 'bolt/dist/legacy/commands/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/index'>
}
declare module 'bolt/dist/legacy/commands/info.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/info'>
}
declare module 'bolt/dist/legacy/commands/init.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/init'>
}
declare module 'bolt/dist/legacy/commands/install.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/install'>
}
declare module 'bolt/dist/legacy/commands/licenses/generateDisclaimer.js' {
  declare module.exports: $Exports<
    'bolt/dist/legacy/commands/licenses/generateDisclaimer'
  >
}
declare module 'bolt/dist/legacy/commands/licenses/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/licenses/index'>
}
declare module 'bolt/dist/legacy/commands/licenses/list.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/licenses/list'>
}
declare module 'bolt/dist/legacy/commands/link.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/link'>
}
declare module 'bolt/dist/legacy/commands/lint.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/lint'>
}
declare module 'bolt/dist/legacy/commands/list.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/list'>
}
declare module 'bolt/dist/legacy/commands/login.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/login'>
}
declare module 'bolt/dist/legacy/commands/logout.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/logout'>
}
declare module 'bolt/dist/legacy/commands/normalize.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/normalize'>
}
declare module 'bolt/dist/legacy/commands/outdated.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/outdated'>
}
declare module 'bolt/dist/legacy/commands/owner/add.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/owner/add'>
}
declare module 'bolt/dist/legacy/commands/owner/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/owner/index'>
}
declare module 'bolt/dist/legacy/commands/owner/list.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/owner/list'>
}
declare module 'bolt/dist/legacy/commands/owner/remove.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/owner/remove'>
}
declare module 'bolt/dist/legacy/commands/pack.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/pack'>
}
declare module 'bolt/dist/legacy/commands/project/add.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/project/add'>
}
declare module 'bolt/dist/legacy/commands/project/exec.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/project/exec'>
}
declare module 'bolt/dist/legacy/commands/project/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/project/index'>
}
declare module 'bolt/dist/legacy/commands/project/remove.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/project/remove'>
}
declare module 'bolt/dist/legacy/commands/project/run.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/project/run'>
}
declare module 'bolt/dist/legacy/commands/project/upgrade.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/project/upgrade'>
}
declare module 'bolt/dist/legacy/commands/publish.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/publish'>
}
declare module 'bolt/dist/legacy/commands/publishLock.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/publishLock'>
}
declare module 'bolt/dist/legacy/commands/publishUnlock.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/publishUnlock'>
}
declare module 'bolt/dist/legacy/commands/remove.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/remove'>
}
declare module 'bolt/dist/legacy/commands/run.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/run'>
}
declare module 'bolt/dist/legacy/commands/tag/add.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/tag/add'>
}
declare module 'bolt/dist/legacy/commands/tag/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/tag/index'>
}
declare module 'bolt/dist/legacy/commands/tag/list.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/tag/list'>
}
declare module 'bolt/dist/legacy/commands/tag/remove.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/tag/remove'>
}
declare module 'bolt/dist/legacy/commands/team/add.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/team/add'>
}
declare module 'bolt/dist/legacy/commands/team/create.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/team/create'>
}
declare module 'bolt/dist/legacy/commands/team/destroy.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/team/destroy'>
}
declare module 'bolt/dist/legacy/commands/team/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/team/index'>
}
declare module 'bolt/dist/legacy/commands/team/list.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/team/list'>
}
declare module 'bolt/dist/legacy/commands/team/remove.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/team/remove'>
}
declare module 'bolt/dist/legacy/commands/test.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/test'>
}
declare module 'bolt/dist/legacy/commands/unlink.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/unlink'>
}
declare module 'bolt/dist/legacy/commands/upgrade.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/upgrade'>
}
declare module 'bolt/dist/legacy/commands/upgradeInteractive.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/upgradeInteractive'>
}
declare module 'bolt/dist/legacy/commands/version.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/version'>
}
declare module 'bolt/dist/legacy/commands/versions.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/versions'>
}
declare module 'bolt/dist/legacy/commands/why.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/why'>
}
declare module 'bolt/dist/legacy/commands/workspace/add.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspace/add'>
}
declare module 'bolt/dist/legacy/commands/workspace/exec.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspace/exec'>
}
declare module 'bolt/dist/legacy/commands/workspace/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspace/index'>
}
declare module 'bolt/dist/legacy/commands/workspace/link.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspace/link'>
}
declare module 'bolt/dist/legacy/commands/workspace/remove.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspace/remove'>
}
declare module 'bolt/dist/legacy/commands/workspace/run.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspace/run'>
}
declare module 'bolt/dist/legacy/commands/workspace/unlink.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspace/unlink'>
}
declare module 'bolt/dist/legacy/commands/workspace/upgrade.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspace/upgrade'>
}
declare module 'bolt/dist/legacy/commands/workspaces/add.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspaces/add'>
}
declare module 'bolt/dist/legacy/commands/workspaces/exec.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspaces/exec'>
}
declare module 'bolt/dist/legacy/commands/workspaces/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspaces/index'>
}
declare module 'bolt/dist/legacy/commands/workspaces/remove.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspaces/remove'>
}
declare module 'bolt/dist/legacy/commands/workspaces/run.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspaces/run'>
}
declare module 'bolt/dist/legacy/commands/workspaces/upgrade.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/commands/workspaces/upgrade'>
}
declare module 'bolt/dist/legacy/Config.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/Config'>
}
declare module 'bolt/dist/legacy/constants.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/constants'>
}
declare module 'bolt/dist/legacy/functions/getDependencyGraph.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/functions/getDependencyGraph'>
}
declare module 'bolt/dist/legacy/functions/getDependentsGraph.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/functions/getDependentsGraph'>
}
declare module 'bolt/dist/legacy/functions/getProject.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/functions/getProject'>
}
declare module 'bolt/dist/legacy/functions/getWorkspaces.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/functions/getWorkspaces'>
}
declare module 'bolt/dist/legacy/functions/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/functions/index'>
}
declare module 'bolt/dist/legacy/functions/runWorkspaceTasks.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/functions/runWorkspaceTasks'>
}
declare module 'bolt/dist/legacy/functions/updatePackageVersions.js' {
  declare module.exports: $Exports<
    'bolt/dist/legacy/functions/updatePackageVersions'
  >
}
declare module 'bolt/dist/legacy/functions/updateWorkspaceDependencies.js' {
  declare module.exports: $Exports<
    'bolt/dist/legacy/functions/updateWorkspaceDependencies'
  >
}
declare module 'bolt/dist/legacy/generators/license.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/generators/license'>
}
declare module 'bolt/dist/legacy/index.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/index'>
}
declare module 'bolt/dist/legacy/Package.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/Package'>
}
declare module 'bolt/dist/legacy/Project.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/Project'>
}
declare module 'bolt/dist/legacy/Repository.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/Repository'>
}
declare module 'bolt/dist/legacy/types.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/types'>
}
declare module 'bolt/dist/legacy/utils/addDependenciesToPackages.js' {
  declare module.exports: $Exports<
    'bolt/dist/legacy/utils/addDependenciesToPackages'
  >
}
declare module 'bolt/dist/legacy/utils/changes.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/changes'>
}
declare module 'bolt/dist/legacy/utils/errors.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/errors'>
}
declare module 'bolt/dist/legacy/utils/execCommand.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/execCommand'>
}
declare module 'bolt/dist/legacy/utils/fs.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/fs'>
}
declare module 'bolt/dist/legacy/utils/git.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/git'>
}
declare module 'bolt/dist/legacy/utils/globs.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/globs'>
}
declare module 'bolt/dist/legacy/utils/jsonModifier.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/jsonModifier'>
}
declare module 'bolt/dist/legacy/utils/locks.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/locks'>
}
declare module 'bolt/dist/legacy/utils/logger.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/logger'>
}
declare module 'bolt/dist/legacy/utils/messages.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/messages'>
}
declare module 'bolt/dist/legacy/utils/npm.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/npm'>
}
declare module 'bolt/dist/legacy/utils/options.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/options'>
}
declare module 'bolt/dist/legacy/utils/processes.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/processes'>
}
declare module 'bolt/dist/legacy/utils/promises.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/promises'>
}
declare module 'bolt/dist/legacy/utils/prompts.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/prompts'>
}
declare module 'bolt/dist/legacy/utils/removeDependenciesFromPackages.js' {
  declare module.exports: $Exports<
    'bolt/dist/legacy/utils/removeDependenciesFromPackages'
  >
}
declare module 'bolt/dist/legacy/utils/symlinkPackageDependencies.js' {
  declare module.exports: $Exports<
    'bolt/dist/legacy/utils/symlinkPackageDependencies'
  >
}
declare module 'bolt/dist/legacy/utils/upgradeDependenciesInPackages.js' {
  declare module.exports: $Exports<
    'bolt/dist/legacy/utils/upgradeDependenciesInPackages'
  >
}
declare module 'bolt/dist/legacy/utils/validateProject.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/validateProject'>
}
declare module 'bolt/dist/legacy/utils/yarn.js' {
  declare module.exports: $Exports<'bolt/dist/legacy/utils/yarn'>
}
declare module 'bolt/dist/modern/cli.js' {
  declare module.exports: $Exports<'bolt/dist/modern/cli'>
}
declare module 'bolt/dist/modern/commands/add.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/add'>
}
declare module 'bolt/dist/modern/commands/autoclean.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/autoclean'>
}
declare module 'bolt/dist/modern/commands/bin.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/bin'>
}
declare module 'bolt/dist/modern/commands/build.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/build'>
}
declare module 'bolt/dist/modern/commands/cache/clean.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/cache/clean'>
}
declare module 'bolt/dist/modern/commands/cache/dir.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/cache/dir'>
}
declare module 'bolt/dist/modern/commands/cache/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/cache/index'>
}
declare module 'bolt/dist/modern/commands/cache/list.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/cache/list'>
}
declare module 'bolt/dist/modern/commands/check.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/check'>
}
declare module 'bolt/dist/modern/commands/config/current.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/config/current'>
}
declare module 'bolt/dist/modern/commands/config/delete.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/config/delete'>
}
declare module 'bolt/dist/modern/commands/config/get.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/config/get'>
}
declare module 'bolt/dist/modern/commands/config/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/config/index'>
}
declare module 'bolt/dist/modern/commands/config/list.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/config/list'>
}
declare module 'bolt/dist/modern/commands/config/set.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/config/set'>
}
declare module 'bolt/dist/modern/commands/create.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/create'>
}
declare module 'bolt/dist/modern/commands/doc.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/doc'>
}
declare module 'bolt/dist/modern/commands/exec.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/exec'>
}
declare module 'bolt/dist/modern/commands/format.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/format'>
}
declare module 'bolt/dist/modern/commands/generate.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/generate'>
}
declare module 'bolt/dist/modern/commands/global/add.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/global/add'>
}
declare module 'bolt/dist/modern/commands/global/bin.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/global/bin'>
}
declare module 'bolt/dist/modern/commands/global/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/global/index'>
}
declare module 'bolt/dist/modern/commands/global/list.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/global/list'>
}
declare module 'bolt/dist/modern/commands/global/remove.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/global/remove'>
}
declare module 'bolt/dist/modern/commands/global/upgrade.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/global/upgrade'>
}
declare module 'bolt/dist/modern/commands/help.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/help'>
}
declare module 'bolt/dist/modern/commands/import.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/import'>
}
declare module 'bolt/dist/modern/commands/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/index'>
}
declare module 'bolt/dist/modern/commands/info.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/info'>
}
declare module 'bolt/dist/modern/commands/init.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/init'>
}
declare module 'bolt/dist/modern/commands/install.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/install'>
}
declare module 'bolt/dist/modern/commands/licenses/generateDisclaimer.js' {
  declare module.exports: $Exports<
    'bolt/dist/modern/commands/licenses/generateDisclaimer'
  >
}
declare module 'bolt/dist/modern/commands/licenses/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/licenses/index'>
}
declare module 'bolt/dist/modern/commands/licenses/list.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/licenses/list'>
}
declare module 'bolt/dist/modern/commands/link.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/link'>
}
declare module 'bolt/dist/modern/commands/lint.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/lint'>
}
declare module 'bolt/dist/modern/commands/list.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/list'>
}
declare module 'bolt/dist/modern/commands/login.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/login'>
}
declare module 'bolt/dist/modern/commands/logout.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/logout'>
}
declare module 'bolt/dist/modern/commands/normalize.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/normalize'>
}
declare module 'bolt/dist/modern/commands/outdated.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/outdated'>
}
declare module 'bolt/dist/modern/commands/owner/add.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/owner/add'>
}
declare module 'bolt/dist/modern/commands/owner/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/owner/index'>
}
declare module 'bolt/dist/modern/commands/owner/list.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/owner/list'>
}
declare module 'bolt/dist/modern/commands/owner/remove.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/owner/remove'>
}
declare module 'bolt/dist/modern/commands/pack.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/pack'>
}
declare module 'bolt/dist/modern/commands/project/add.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/project/add'>
}
declare module 'bolt/dist/modern/commands/project/exec.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/project/exec'>
}
declare module 'bolt/dist/modern/commands/project/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/project/index'>
}
declare module 'bolt/dist/modern/commands/project/remove.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/project/remove'>
}
declare module 'bolt/dist/modern/commands/project/run.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/project/run'>
}
declare module 'bolt/dist/modern/commands/project/upgrade.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/project/upgrade'>
}
declare module 'bolt/dist/modern/commands/publish.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/publish'>
}
declare module 'bolt/dist/modern/commands/publishLock.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/publishLock'>
}
declare module 'bolt/dist/modern/commands/publishUnlock.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/publishUnlock'>
}
declare module 'bolt/dist/modern/commands/remove.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/remove'>
}
declare module 'bolt/dist/modern/commands/run.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/run'>
}
declare module 'bolt/dist/modern/commands/tag/add.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/tag/add'>
}
declare module 'bolt/dist/modern/commands/tag/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/tag/index'>
}
declare module 'bolt/dist/modern/commands/tag/list.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/tag/list'>
}
declare module 'bolt/dist/modern/commands/tag/remove.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/tag/remove'>
}
declare module 'bolt/dist/modern/commands/team/add.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/team/add'>
}
declare module 'bolt/dist/modern/commands/team/create.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/team/create'>
}
declare module 'bolt/dist/modern/commands/team/destroy.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/team/destroy'>
}
declare module 'bolt/dist/modern/commands/team/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/team/index'>
}
declare module 'bolt/dist/modern/commands/team/list.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/team/list'>
}
declare module 'bolt/dist/modern/commands/team/remove.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/team/remove'>
}
declare module 'bolt/dist/modern/commands/test.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/test'>
}
declare module 'bolt/dist/modern/commands/unlink.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/unlink'>
}
declare module 'bolt/dist/modern/commands/upgrade.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/upgrade'>
}
declare module 'bolt/dist/modern/commands/upgradeInteractive.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/upgradeInteractive'>
}
declare module 'bolt/dist/modern/commands/version.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/version'>
}
declare module 'bolt/dist/modern/commands/versions.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/versions'>
}
declare module 'bolt/dist/modern/commands/why.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/why'>
}
declare module 'bolt/dist/modern/commands/workspace/add.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspace/add'>
}
declare module 'bolt/dist/modern/commands/workspace/exec.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspace/exec'>
}
declare module 'bolt/dist/modern/commands/workspace/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspace/index'>
}
declare module 'bolt/dist/modern/commands/workspace/link.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspace/link'>
}
declare module 'bolt/dist/modern/commands/workspace/remove.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspace/remove'>
}
declare module 'bolt/dist/modern/commands/workspace/run.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspace/run'>
}
declare module 'bolt/dist/modern/commands/workspace/unlink.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspace/unlink'>
}
declare module 'bolt/dist/modern/commands/workspace/upgrade.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspace/upgrade'>
}
declare module 'bolt/dist/modern/commands/workspaces/add.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspaces/add'>
}
declare module 'bolt/dist/modern/commands/workspaces/exec.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspaces/exec'>
}
declare module 'bolt/dist/modern/commands/workspaces/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspaces/index'>
}
declare module 'bolt/dist/modern/commands/workspaces/remove.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspaces/remove'>
}
declare module 'bolt/dist/modern/commands/workspaces/run.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspaces/run'>
}
declare module 'bolt/dist/modern/commands/workspaces/upgrade.js' {
  declare module.exports: $Exports<'bolt/dist/modern/commands/workspaces/upgrade'>
}
declare module 'bolt/dist/modern/Config.js' {
  declare module.exports: $Exports<'bolt/dist/modern/Config'>
}
declare module 'bolt/dist/modern/constants.js' {
  declare module.exports: $Exports<'bolt/dist/modern/constants'>
}
declare module 'bolt/dist/modern/functions/getDependencyGraph.js' {
  declare module.exports: $Exports<'bolt/dist/modern/functions/getDependencyGraph'>
}
declare module 'bolt/dist/modern/functions/getDependentsGraph.js' {
  declare module.exports: $Exports<'bolt/dist/modern/functions/getDependentsGraph'>
}
declare module 'bolt/dist/modern/functions/getProject.js' {
  declare module.exports: $Exports<'bolt/dist/modern/functions/getProject'>
}
declare module 'bolt/dist/modern/functions/getWorkspaces.js' {
  declare module.exports: $Exports<'bolt/dist/modern/functions/getWorkspaces'>
}
declare module 'bolt/dist/modern/functions/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/functions/index'>
}
declare module 'bolt/dist/modern/functions/runWorkspaceTasks.js' {
  declare module.exports: $Exports<'bolt/dist/modern/functions/runWorkspaceTasks'>
}
declare module 'bolt/dist/modern/functions/updatePackageVersions.js' {
  declare module.exports: $Exports<
    'bolt/dist/modern/functions/updatePackageVersions'
  >
}
declare module 'bolt/dist/modern/functions/updateWorkspaceDependencies.js' {
  declare module.exports: $Exports<
    'bolt/dist/modern/functions/updateWorkspaceDependencies'
  >
}
declare module 'bolt/dist/modern/generators/license.js' {
  declare module.exports: $Exports<'bolt/dist/modern/generators/license'>
}
declare module 'bolt/dist/modern/index.js' {
  declare module.exports: $Exports<'bolt/dist/modern/index'>
}
declare module 'bolt/dist/modern/Package.js' {
  declare module.exports: $Exports<'bolt/dist/modern/Package'>
}
declare module 'bolt/dist/modern/Project.js' {
  declare module.exports: $Exports<'bolt/dist/modern/Project'>
}
declare module 'bolt/dist/modern/Repository.js' {
  declare module.exports: $Exports<'bolt/dist/modern/Repository'>
}
declare module 'bolt/dist/modern/types.js' {
  declare module.exports: $Exports<'bolt/dist/modern/types'>
}
declare module 'bolt/dist/modern/utils/addDependenciesToPackages.js' {
  declare module.exports: $Exports<
    'bolt/dist/modern/utils/addDependenciesToPackages'
  >
}
declare module 'bolt/dist/modern/utils/changes.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/changes'>
}
declare module 'bolt/dist/modern/utils/errors.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/errors'>
}
declare module 'bolt/dist/modern/utils/execCommand.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/execCommand'>
}
declare module 'bolt/dist/modern/utils/fs.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/fs'>
}
declare module 'bolt/dist/modern/utils/git.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/git'>
}
declare module 'bolt/dist/modern/utils/globs.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/globs'>
}
declare module 'bolt/dist/modern/utils/jsonModifier.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/jsonModifier'>
}
declare module 'bolt/dist/modern/utils/locks.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/locks'>
}
declare module 'bolt/dist/modern/utils/logger.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/logger'>
}
declare module 'bolt/dist/modern/utils/messages.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/messages'>
}
declare module 'bolt/dist/modern/utils/npm.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/npm'>
}
declare module 'bolt/dist/modern/utils/options.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/options'>
}
declare module 'bolt/dist/modern/utils/processes.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/processes'>
}
declare module 'bolt/dist/modern/utils/promises.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/promises'>
}
declare module 'bolt/dist/modern/utils/prompts.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/prompts'>
}
declare module 'bolt/dist/modern/utils/removeDependenciesFromPackages.js' {
  declare module.exports: $Exports<
    'bolt/dist/modern/utils/removeDependenciesFromPackages'
  >
}
declare module 'bolt/dist/modern/utils/symlinkPackageDependencies.js' {
  declare module.exports: $Exports<
    'bolt/dist/modern/utils/symlinkPackageDependencies'
  >
}
declare module 'bolt/dist/modern/utils/upgradeDependenciesInPackages.js' {
  declare module.exports: $Exports<
    'bolt/dist/modern/utils/upgradeDependenciesInPackages'
  >
}
declare module 'bolt/dist/modern/utils/validateProject.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/validateProject'>
}
declare module 'bolt/dist/modern/utils/yarn.js' {
  declare module.exports: $Exports<'bolt/dist/modern/utils/yarn'>
}
declare module 'bolt/index' {
  declare module.exports: $Exports<'bolt'>
}
declare module 'bolt/index.js' {
  declare module.exports: $Exports<'bolt'>
}
