// http://naturalnode.github.io/natural/brill_pos_tagger.html

export var tagLegend = {
  CC: "Coord Conjunction",
  CD: "Cardinal number",
  DT: "Determiner",
  EX: "Existential there",
  FW: "Foreign Word",
  IN: "Preposition",
  JJ: "Adjective",
  JJR: "Adjective, comparative",
  JJS: "Adjective, superlative",
  LS: "List item marker",
  MD: "Modal",
  NN: "Noun, singular or mass",
  NNP: "Proper noun, singular",
  NNPS: "Proper noun, plural",
  NNS: "Noun, plural",
  POS: "Possessive ending",
  PDT: "Predeterminer",
  PP$: "Possessive pronoun",
  PRP: "Personal pronoun",
  RB: "Adverb",
  RBR: "Adverb, comparative",
  RBS: "Adverb, superlative",
  RP: "Particle",
  SYM: "Symbol",
  TO: '"to"',
  UH: "Interjection",
  VB: "Verb, base form",
  VBD: "Verb, past tense",
  VBG: "Verb, gerund",
  VBN: "Verb, past part",
  VBP: "Verb, present",
  VBZ: "Verb, present",
  WDT: "Wh-determiner",
  WP: "Wh pronoun",
  WP$: "Possessive-Wh",
  WRB: "Wh-adverb"
} as const;

export type PosTag = keyof typeof tagLegend;

export var tagMap: Record<PosTag, string[]> = {
  CC: [],
  CD: [],
  DT: [],
  EX: [],
  FW: [],
  IN: [],
  JJ: [],
  JJR: [],
  JJS: [],
  LS: [],
  MD: [],
  NN: [],
  NNP: [],
  NNPS: [],
  NNS: [],
  POS: [],
  PDT: [],
  PP$: [],
  PRP: [],
  RB: [],
  RBR: [],
  RBS: [],
  RP: [],
  SYM: [],
  TO: [],
  UH: [],
  VB: [],
  VBD: [],
  VBG: [],
  VBN: [],
  VBP: [],
  VBZ: [],
  WDT: [],
  WP: [],
  WP$: [],
  WRB: []
};
