version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./dist:/usr/src/app/dist

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
