name: CodeQL

on:
  push:
  pull_request:
  schedule:
    - cron: "30 1 * * *"

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build ./cmd/downwrite

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
