name: E2E Testing
on: [pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      CI: true
      NO_HTTPS: true
      NODE_ENV: test
      SECRET_KEY: "foo"
      NEXT_TELEMETRY_DISABLED: 1
    strategy:
      matrix:
        node-version: [12.x]

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Build Project for Testing
        run: yarn build
      - name: Run Puppeteer
        run: yarn test:e2e
